var data =

    {
        "generos":[
            {
                "id":"1",
                "artista_id":"0001",
                "nombre":"Led Zepelin",
                "grupo":"Led Zepelin",
                "cancion": "Rock And Roll",
                "genero":"Rock",
                "duracion": "3.11",
            },
            {
                "id":"1",
                "artista_id":"0002",
                "nombre":"Juan De LaRosa",
                "grupo":"Triana",
                "cancion": "Tu frialdad",
                "genero":"Rock",
                "duracion": "4.23",
            },
            {
                "id":"1",
                "artista_id":"0003",
                "nombre":"Alan Helm",
                "grupo":"Deep Purple",
                "cancion": "Soldier of Fortune",
                "genero":"Rock",
                "duracion": "3.17",
            },
            {
                "id":"2",
                "artista_id":"0004",
                "nombre":"Zazz",
                "grupo":"Zazz",
                "cancion": "Eblouie par la Nuit",
                "genero":"Jazz",
                "duracion": "2.53",
            },
            {
                "id":"2",
                "artista_id":"0005",
                "nombre":"Miles Davis",
                "grupo":"Kind of Blue",
                "cancion": "Blue in Green",
                "genero":"Jazz",
                "duracion": "5.37",
            },
            {
                "id":"2",
                "artista_id":"0006",
                "nombre":"Ella and Louis",
                "grupo":"Ella and Louis",
                "cancion": "What a Wonderful World",
                "genero":"Jazz",
                "duracion": "4.58",
            },
            {
                "id":"3",
                "artista_id":"0007",
                "nombre":"Vangelis",
                "grupo":"Vangelis",
                "cancion": "Carros de Fuego",
                "genero":"Classical",
                "duracion": "3.21",
            },
            {
                "id":"3",
                "artista_id":"0008",
                "nombre":"Beethoven",
                "grupo":"Beethoven",
                "cancion": "Para Elisa",
                "genero":"Classical",
                "duracion": "4.03",
            },
            {
                "id":"3",
                "artista_id":"0009",
                "nombre":"Chopin",
                "grupo":"Chopin",
                "cancion": "Gran Valse Brillante",
                "genero":"Classical",
                "duracion": "5.54",
            },
            {
                "id":"4",
                "artista_id":"0010",
                "nombre":"Michael Jackson",
                "grupo":"Michael Jackson",
                "cancion": "Thriller",
                "genero":"Soul",
                "duracion": "5.57",
            },
            {
                "id":"4",
                "artista_id":"0011",
                "nombre":"Solomon Burke",
                "grupo":"Solomon Burke",
                "cancion": "Cry To Me",
                "genero":"Soul",
                "duracion": "2.43",
            },
            {
                "id":"4",
                "artista_id":"0012",
                "nombre":"Amy Winehouse",
                "grupo":"Amy Winehouse",
                "cancion": "Rehab",
                "genero":"Soul",
                "duracion": "3.41",
            },
            {
                "id":"5",
                "artista_id":"0013",
                "nombre":"Justin Bieber",
                "grupo":"Justin Bieber",
                "cancion": "Sorry",
                "genero":"Pop",
                "duracion": "3.25",
            },
            {
                "id":"5",
                "artista_id":"0014",
                "nombre":"Justin Bieber",
                "grupo":"Justin Bieber",
                "cancion": "Despacito",
                "genero":"Pop",
                "duracion": "4.41",
            },
            {
                "id":"5",
                "artista_id":"0015",
                "nombre":"Ariana Grande ft. Iggy Azalea",
                "grupo":"Ariana Grande",
                "cancion": "Problem",
                "genero":"Pop",
                "duracion": "3.87",
            },




        ]
    }